version: '3.8'

services:
  backend:
    build: ./
    image: ecom-golang
    container_name: golang-ecom
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    volumes:
      - /home/projects/logs/backend/errors.log:/app/internal/logs/errors.log

  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
